apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}

