apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-controller-manager
  namespace: {{ .Release.Namespace }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
