apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.serviceAccountAnnotations }}
{{ toYaml .Values.serviceAccountAnnotations | indent 4 }}
{{- end }}
