images:
  machine-controller-manager: image-repository:image-tag

replicas: 1

podAnnotations: {}

podLabels: {}

providerName: provider-foo

namespace:
  uid: uuid-of-namespace

metricsPort: 10258

vpa:
  enabled: true
  updatePolicy:
    # do not interrupt MCM, workaround https://jira.tidbcloud.com/browse/DM-1037
    updateMode: "Initial"
